// Code generated by Slice Machine. DO NOT EDIT.

import Columns from './Columns';
import Images from './Images';
import TextBlock from './TextBlock';

export {
	Columns,
	Images,
	TextBlock,
};

export const components = {
	columns: Columns,
	images: Images,
	text_block: TextBlock,
};
